version: '3.1'
services:
  www:
    build: .
    image: redlock-web-2.0
    ports:
      - "7077:80"
    links:
      - db
    networks:
      - default

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: Redlock
      MYSQL_USER: marvel
      MYSQL_PASSWORD: 128chars
      MYSQL_ROOT_PASSWORD: 128chars
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - default
